### ISSUE TITLE
Overriding default QGIS behavior causes other plugins to fail

### ISSUE THREAD

**Issue by MieWinstrup** [PANOimagen/profiletool#13]
Normally qgis.core.QgsProject.read is able to read a node - and many plugins rely on that fact. Therefore, changing the default behavior can make other plugins fail. This happens in https://github.com/PANOimagen/profiletool/blob/29259cbe88eaef0058f7c837d628b1fddf5079c4/apicompat/qgsproject.py#L53-L59 

This is a screenshot that shows an example where it fails because filename is not a string:
![qgis2 18_qdomnode](https://user-images.githubusercontent.com/16276034/48224006-db628080-e398-11e8-8a4c-181312cbc3a6.PNG)

**Comment by JaviBecerra** [comment]
Hi @MieWinstrup,

ProfileTool was refactored to be QGis3.x compatible and we use a compatibility module (apicompat.py) to keep it running properly in 2.x. This problem should not exist in QGis 3.x (given that the apicompat module is not used then).
We understand where the issue comes from and have a quick fix in mind, however we have not been able to reproduce the issue with Kortforsyning, could you provide a step-by-step guide to reproduce the problem so that we can verify the fix is working as expected?
Best regards,
Javier

**Comment by JaviBecerra** [comment]
If you want to try a fix while we get this properly checked, you can edit profiletool/apicompat/qgsproject.py and replace the read function with the following:
I think that should be enough to solve the issue.
```
def read(self, param=None):   
    if param:
        try:
            return original_QgsProject_read(self, QFileInfo(param))
        except TypeError:
            return original_QgsProject_read(self, param)
    else:
        return original_QgsProject_read(self)
```

**Comment by JaviBecerra** [comment]
Hi @MieWinstrup,
Thanks for your help; we have uploaded ProfileTool plugin version 4.1.4. to QGis repositories that should address this issue.
I am closing this now, please feel free to reopen it if you find any problem.
Regards
