### ISSUE TITLE
I'm getting an error when trying to save as - 3d line - DXF dxfwrite

### ISSUE THREAD

**Issue by conorferguson** [PANOimagen/profiletool#15]
Hello,

I'm getting an error when trying to save as - 3d line - DXF

the "dxfwrite" program ... some error in the base.py code

![save as dxf error](https://user-images.githubusercontent.com/43569387/51898032-52178480-23b0-11e9-91fc-6bec439124e1.JPG)

NOTE: i am not a coder so i don't know what i'm doing... however, i figured out that user:mozman
wrote the dxfwrite code and saw a message on his user page that it's outdated. perhaps this has something to do with it???

![mozman message](https://user-images.githubusercontent.com/43569387/51898312-f13c7c00-23b0-11e9-87fe-79bd27c5cad6.JPG)

(https://github.com/mozman)

i saw that this issue is related to #2 and i read that issue. user:veragreen said she could export to dxf if it was a temporary polyline. i tried that also and have the same error.

**Comment by JaviBecerra** [comment]
Hi @conorferguson,
Thanks for reporting!
Could you give us some more information so that we can reproduce the issue? At least qgis version and platform (windows, mac, linux) and it would be great if you could provide a minimal dataset to help us reproduce your problem.
Thanks for the pointer to ezdxf, we will consider switching in the near future.

**Comment by conorferguson** [comment]
qgis version: madeira 3.4.4 
platform: windows

minimal dataset - i hope you can download it:
[minimum dataset.zip](https://github.com/PANOimagen/profiletool/files/2808381/minimum.dataset.zip)

**Comment by JaviBecerra** [comment]
Thanks @conorferguson, we have been able to reproduce the issue with your data.
It seems related to null values in the raster layer, we will see to get them properly handled by the dxf exporter.
In the meantime, you can remove the null values from the raster layer (replacing them with a value of your choice) using for instance the r.null filter from grass (that you can run directly from QGis Processing ToolBox), in order to get the profiles exported properly.
Regards

**Comment by conorferguson** [comment]
Thanks for the info. I replaced the null values and i managed to export. The problem now is that, when I open the dxf, i only see a straight line. It doesn't seem to export the "Interpolated profile".

**Comment by JaviBecerra** [comment]
Hi @conorferguson, @marcodallago,
This may not be evident from the user interface, but the dxf exporter does not behave like the svg and png exporters. Svg and png export the profile graph, while dxf exports a 3D polyline with the x, y, z coordinates in every point (i.e. it adds the z coordinate to every point in the input data).
Depending on the SW you are using to open the dxf, it may or may not support the 3D coordinates on the exported output.
We have checked the generated dxf and z coordinate is present and with the right values, but not every tool seems to support it or show anything else than the xy view.
Please confirm that this is the behaviour your are experienced (try to extract the profile something other than a straight line in xy and see if it matches what you retrieve in dxf). If so the dxf exported behaves as it was originally intended, and we will try to make it clear in the UI.

**Comment by marcodallago** [comment]
Hi @JaviBecerra , I managed to open it inside autocad. Even tough opening directly by double clicking on the file on finder, it does not open the file, by using the open command inside autocad the program managed to open it up.

One lacking feature to me would be a simply checkbox that will allow me to export also the section in 2d mode with the z = zero reference line. Would be super great to have instead of doing it manually for each section. I have multiple ( about 50 ) sections to cut and align in autocad and it is kinda a nightmare ahaha

**Comment by JaviBecerra** [comment]
Commit ce38ca2 should fix the original issue regarding undefined values in the raster dtm. We will be updating the plugin on QGis repos asap.
