### ISSUE TITLE
Null geometry cannot be converted to a point

### ISSUE THREAD

**Issue by zsiki** [PANOimagen/profiletool#19]
When _Link mouse position on graph with canvas_ is on and moving the mouse to end of the profile I get an error:

ValueError: Null geometry cannot be converted to a point. 
Traceback (most recent call last):
  File "/home/siki/.local/share/QGIS/QGIS3/profiles/default/python/plugins/profiletool/tools/profiletool_core.py", line 415, in mouseMovedPyQtGraph
    self.updateCursorOnMap(xtoplot)
  File "/home/siki/.local/share/QGIS/QGIS3/profiles/default/python/plugins/profiletool/tools/profiletool_core.py", line 245, in updateCursorOnMap
    pointprojected = geom.interpolate(x).asPoint()
ValueError: Null geometry cannot be converted to a point.

Python version: 3.6.7 (default, Oct 22 2018, 11:32:17) [GCC 8.2.0] 
QGIS version: 3.4.4-Madeira Madeira, f6ddc62

**Comment by JaviBecerra** [comment]
Hi @zsiki,
Thanks for the report. 
We have not been able to reproduce the issue, what plugin version are you using? We have updated ProfileTool on the QGis repositories just a few hours ago, can you reproduce the issue with the latest version (4.1.5)?
If you are still finding the issue with the latest version, please provide a minimum sample dataset where you can reproduce the issue, so that we can check it out.
Regards,
Javier

**Comment by zsiki** [comment]
I used 4.1.4 with SRTM when the error happened. Installing the new version (4.1.5) I can't reproduce the error with the same data set. Thanks.
