### ISSUE TITLE
DXF Export Issue with DXFFloat

### ISSUE THREAD

**Issue by veragreen119** [PANOimagen/profiletool#2]
We saw that there was a bug related to dxf export recently reported and marked as fixed but we are unable to export to dxf from both Q 2.18 and 3 when the line is either a temporary polyline with more than 2 vertexes or a selected polyline.  It does work for a supper simple temporary polyline with only 2 vertexes.
The error is:
`			  File "...\profiletool\dxfwrite\base.py", line 237, in __init__
			    super(DXFFloat, self).__init__(float(value), group_code)
			TypeError: float() argument must be a string or a number`

class DXFAngle has the same issue.

**Comment by JaviBecerra** [comment]
Hi veragreen119,
Thanks for reporting.
We have not been able to reproduce the issue with QGis 2.18 (have not tried on QGis 3 yet). Could you provide a minimal data sample showing the behaviour you describe?

**Comment by veragreen119** [comment]
While preparing a data sample for you we found the export worked. Differences:
ORIGINAL DATA VS DATA SAMPLE
virtual raster mosaic vs source raster file
raster resolution 1m vs 15m
line source postGIS vs .shp

We will do some more testing to isolate which one of these differences caused the issue and will let you know.

Thanks Much,
Vera

**Comment by veragreen119** [comment]
We have done some more testing:
The tool works fine with a postGIS layer
Tool works fine on a small 1m raster
Tool works fine on a large 15m raster catalogue
Tool does NOT work on a large 1m raster (line length of 35Km).  Also autocad can't use results at this density anyway (it crashes).  Based on this I would suggest as an enhancement to the tool that if the point count exceeds a threshold amount the tool automatically decreases the point density.  Alternately, allow the user to set a point density.  I'm not sure what the maximum point count would be but it's less than 35'000.
Thanks,
Vera

**Comment by JaviBecerra** [comment]
Thanks for the feedback @veragreen119.
Right now the interpolating behaviour is to use the same sampling rate as the dtm (i.e. a 1m raster gets polylines sampled each 1m). However, as long as the settings->Full resolution enabled checkbox is off -which is the default behaviour- each segment in the polyline gets a maximum of 1000 points.

We will try with a longer polyline to verify your issue. In the meantime, perhaps you can uncheck the "Interpolated profile" checkbox - that will only sample at the polyline vertices, instead of interpolating at every pixel in the dtm. 

We have to rethink the UI with a better (and more explicit) way to specify the sampling rate, perhaps mixing those two controls into a single slider (minimum means no interpolation, maximum means interpolating at the dtm's sampling rate, something in between means an intermediate interpolation rate).

**Comment by JaviBecerra** [comment]
@veragreen119  we have not been able to reproduce the issue using polylines as big as 103521 points (548km polyline in a 5m dtm).
Could it be that you are running out of memory? 
I am closing the issue, please reopen if you continue experiencing it; in that case a minimal sample to reproduce the problem would be greatly appreciated.
