### ISSUE TITLE
MDAL Compatability

### ISSUE THREAD

**Issue by calumpeden** [PANOimagen/profiletool#22]
It does not seem to be possible to use the profile tool to extract profiles from MDAL layers. It could previously extract layers from mesh layers rendered using the Crayfish plugin however this does not seem to work in QGIS 3.4.0 with the same layers rendered through MDAL. It is however possible that I have just missed something and it does work but I cant figure out how.

**Comment by JaviBecerra** [comment]
Hi @calumpeden,
We added some sanity checks to the code to avoid adding unsupported layer types and may have been a bit more restrictive than we should have...
We will take a look at this asap.

**Comment by calumpeden** [comment]
No worries. Cheers

**Comment by JaviBecerra** [comment]
Actually Crayfish plugin now uses QGis MeshLayer builtin type instead of the custom type they were using in Qgis 2.x. 
We have added support in branch feature/meshlayersupport (commit 97f23d2), @calumpeden can you give it a try?
(Please note that due to our use of QgsMapToolIdentify to actually read the data values the latest QGis 3.6 is required)

**Comment by calumpeden** [comment]
I have tried it with download QGIS 3.6 and It works with mesh layers now. Cheers

**Comment by JaviBecerra** [comment]
Cool, we will be merging this branch into master and updating the plugin version in QGis repos shortly.
