### ISSUE TITLE
Error on install

### ISSUE THREAD

**Issue by shmulik90** [PANOimagen/profiletool#24]
Hi there,

Somehow the install cannot find a package it needs- any ideas? 
![grafik](https://user-images.githubusercontent.com/38791059/56828557-2711c500-6827-11e9-890a-7508c1367735.png)

**Comment by JaviBecerra** [comment]
Hi @shmulik90,
It seems that your QGis does not have PyQt installed. Did you use the advanced installer form Os4geo? If so, you should be sure to check the PyQt5 (I'm assuming you are using QGis 3.x here) library during installation.
Are you having that same issue with any other plugin? This message should be all around for any python-based plugin that you try to use if PyQt.QtCore is actually not available in your installation.

**Comment by JaviBecerra** [comment]
Hi @shmulik90,
Do you have any additional feedback? 
I am closing the issue as this seems a problem related to your QGis installation rather than an issue with profiletool itself.

Feel free to reopen it if you think that it is actually specific to this plugin and provide us with some additional feedback to help us address it.
Regards
