### ISSUE TITLE
The profile covers a mcuh longer distance than the layer

### ISSUE THREAD

**Issue by kobusburger** [PANOimagen/profiletool#60]
The profile generated by version 4.20.0 (obtained via a zip file) covers a much longer distance than the layer. The total line length of the layer is about 99km but the profile tool displays 245km (see image). The red dot following the mouse is also not on the line (see image). The layer (shape format) and profile table (csv) is attached.

[Profile.zip](https://github.com/PANOimagen/profiletool/files/6766075/Profile.zip)
![image](https://user-images.githubusercontent.com/6264060/124513690-a45bfb80-dddb-11eb-8c98-015f20286a12.png)
![image](https://user-images.githubusercontent.com/6264060/124513742-c5bce780-dddb-11eb-9da5-927435790e4f.png)

**Comment by nicogodet** [comment]
It is ok on a previous version of profiletool ?

**Comment by nicogodet** [comment]
and could you provide the DEM too ?

**Comment by kobusburger** [comment]
Yes. The I see the same problem with version 3.1.8

**Comment by nicogodet** [comment]
@kobusburger please share the DEM too 

I tested on a DEM I had in stock and a fresh new vector line and profiletool report the correct length

**Comment by kobusburger** [comment]
I created a small project (attached) and it still gives the problem. The profile is for more than 240km but the layer length is about 99km (screen capture). The cursor is sometimes also no on the line. I tested it on QGIS 3.16.8 LTR.

![image](https://user-images.githubusercontent.com/6264060/124728398-da9a9780-df0f-11eb-9dad-804e1a991995.png)
[Profile test project.zip](https://github.com/PANOimagen/profiletool/files/6775717/Profile.test.project.zip)

**Comment by nicogodet** [comment]
Ok got it.
If you plot with "Selected polyline" instead of "Selected layer", distance is OK.

When you use "Selected layer", iterate on all feature to extract vertices and append them in a list.
So first vertex of feature N+1 is just after last vertex of feature N.
And profiletool plot the DEM between all vertices.
That's why you see on canvas, the red dot not on your polyline.

Example:

Between fid 36 and 38
![image](https://user-images.githubusercontent.com/39594821/124756717-1001ae00-df2d-11eb-8881-000ef4278b8e.png)

And if you connect all vertices using a strait line
![image](https://user-images.githubusercontent.com/39594821/124757973-6b806b80-df2e-11eb-8fbb-8e823dc9ef19.png)

So it's not a bug to my opinion, just a bad usage of the plugin.

Sorry for the poor english...

**Comment by kobusburger** [comment]
I think I understand. The lines do not follow each other in the attribute table and therefore the profile is created between vertices that do not have a line between them. If I delete the shorter lines which do not follow each other and just retain the long line segments which do follow each other, then the profile is correct.

**Comment by kobusburger** [comment]
Can you exclude the the sections that do not follow a line?

**Comment by nicogodet** [comment]
I would have to guess which line is the main line, order vertices then draw ?

Or use selected polylines instead of selected layer
