### ISSUE TITLE
how to use this plugin?

### ISSUE THREAD

**Issue by berteh** [PANOimagen/profiletool#8]
hello. I cannot figure out how to use this plugin sorry.

I got an elevation layer (raster TIF), which seems to hold valid height information as the extract > contour function works fine. The elevation information is stored in "Z" attribute.

I can add this layer to profile plugin panel just fine. But how do I then draw or select the profile path (polyline) ? 

1. I tried creating a new vector layer with a few distinct line features (I'm interested in getting multiple profiles from a single map), or with a single polyline... but when I try to add this layer to the plugin layers selection I get an error "active layer is not a profilable layer".

2. I can draw a new temporary polyline from the plugin box, but it has no impact on the profile graph widget.

Any hint, explanation or "how to" for newbies ?
Thanks.
B.

**Comment by berteh** [comment]
got to add: when i draw the temporary line the plugin Table widget is indeed updated with points and elevation. That works. But no graph is displayed in profile tab, and the view coordinates are seemingly all wrong (or in another CRS as the project default).

I run QGIS 3.2.2 on XUbuntu 16.04

**Comment by JaviBecerra** [comment]
Hi @berteh,
If you see the points on the  table view, you should also be seeing the height profile on the profile view :/
This seems like a bug, could you provide a minimal example file (dtm + polyline) so that we can try to reproduce it?
Also, check if you are getting any error messages in the python console, that would give us a good idea about what is going on.
Thanks for taking the time to report this!

**Comment by JaviBecerra** [comment]
Hi @berteh,
Any chance that we can get a minimal data example to reproduce your issue?

**Comment by JaviBecerra** [comment]
Hi @berteh,
I am closing the issue due to lack of feedback, feel free to reopen if you can provide us a sample dataset to reproduce the issue.
Regards.
